/*
 * File: app/store/News.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RSS.store.News', {
    extend: 'Ext.data.Store',

    requires: [
        'RSS.model.News'
    ],

    config: {
        model: 'RSS.model.News',
        storeId: 'News',
        proxy: {
            type: 'jsonp',
            extraParams: {
                v: '1.0',
                num: 100,
                q: ''
            },
            url: 'https://ajax.googleapis.com/ajax/services/feed/load',
            reader: {
                type: 'json',
                rootProperty: 'responseData.feed.entries'
            }
        }
    }
});